#!/bin/bash

# inspired by "https://github.com/webworker01/freshubuntu" repository

DEFAULT_TOOLS_FILE="$(dirname $0)/../resources/defaultToolsList.txt"
CUSTOMIZE_UBUNTU_FILE="$(dirname $0)/customizeUbuntu"

if [ "$EUID" -ne 0 ]; then
    echo -e "\e[41mPlease use sudo or run as root...\e[0m"
    exit
fi

read -p "Upgrade packages? (y/n) " -n 1 DOUPGRADES
echo
if [[ $DOUPGRADES =~ ^[Yy]$ ]]; then
    apt-get update && apt-get -y dist-upgrade
fi

read -p "Install default tools? (y/n) " -n 1 DOEXTRAS
echo
if [[ $DOEXTRAS =~ ^[Yy]$ ]]; then
    tools=""
    while read -r line; do tools="$tools $line"; done < $DEFAULT_TOOLS_FILE
    apt -y install $tools
fi

read -p "Customize ubuntu? (y/n) " -n 1 DOCUSTOMIZE
echo
if [[ $DOCUSTOMIZE =~ ^[Yy]$ ]]; then
    $CUSTOMIZE_UBUNTU_FILE
fi

read -p "Setup git committer? (y/n) " -n 1 DOGITCONFIG
echo
if [[ $DOGITCONFIG =~ ^[Yy]$ ]]; then
    read -p "Enter git user name: " GITUSERNAME
    read -p "Enter git email: " GITEMAIL
    echo ">Username='$GITUSERNAME'"
    echo ">Email='$GITEMAIL'"
    read -p "Set git committer like above? (y/n) " -n 1 CHECKGITCONFIG
        echo
        if [[ $CHECKGITCONFIG =~ ^[Yy]$ ]]; then
            git config --global user.email "$GITEMAIL"
            git config --global user.name "$GITUSERNAME"
        fi
fi

